name: Plugin Build

on:
  push:
    branches: [main]
    paths:
      - "wp-content/plugins/toutefois/**"
      - ".github/workflows/build-and-deploy.yml"
      - "nginx/**"
  pull_request:
    branches: [main]
    paths:
      - "wp-content/plugins/toutefois/**"
      - ".github/workflows/build-and-deploy.yml"
      - "nginx/**"

jobs:
  build-plugin:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: wp-content/plugins/toutefois

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: wp-content/plugins/toutefois/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build plugin assets
        run: yarn build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: toutefois-plugin-build
          path: wp-content/plugins/toutefois/build/**
          if-no-files-found: warn

  deploy-backend:
    name: Deploy to DigitalOcean (Next.js)
    needs: build-plugin
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download plugin build artifact
        uses: actions/download-artifact@v4
        with:
          name: toutefois-plugin-build
          path: wp-content/plugins/toutefois/build
          merge-multiple: true

      - name: Deploy backend files via rsync
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --exclude='.git*' --exclude='frontend/' --exclude='node_modules' --exclude='*.log'
          path: "./"
          remote_path: "/var/www/toutefois_app"
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure WordPress and Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            echo "=== WordPress & Nginx Configuration ==="
            # Configure WordPress
            sudo mkdir -p /var/www/wordpress/wp-content/{plugins,themes,uploads}
            sudo rsync -avz --delete /var/www/toutefois_app/wp-content/plugins/ /var/www/wordpress/wp-content/plugins/
            sudo rsync -avz --delete /var/www/toutefois_app/wp-content/themes/ /var/www/wordpress/wp-content/themes/
            sudo find /var/www/wordpress/wp-content -type d -exec chmod 755 {} \;
            sudo find /var/www/wordpress/wp-content -type f -exec chmod 644 {} \;
            sudo chown -R www-data:www-data /var/www/wordpress/wp-content
            # Configure Nginx for WordPress Admin
            sudo cp /var/www/toutefois_app/nginx/sites-available/admin.toutefois.ca.conf /etc/nginx/sites-available/
            sudo ln -sf /etc/nginx/sites-available/admin.toutefois.ca.conf /etc/nginx/sites-enabled/admin.toutefois.ca.conf
            # Reload services
            sudo systemctl reload nginx
            sudo systemctl reload php8.4-fpm
            echo "=== Backend Deployed Successfully ==="
