# .github/workflows/deploy.yml
name: Deploy to DigitalOcean (Next.js)

on:
  workflow_run:
    workflows: ["Plugin Build"]
    types: [completed]
  workflow_dispatch: {}

jobs:
  deploy-backend:
    # Run only when the triggering workflow (Plugin Build) succeeded and on main branch
    if: >-
      ${{ (github.event_name == 'workflow_dispatch') ||
          (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download plugin build artifact
        uses: actions/download-artifact@v4
        with:
          name: toutefois-plugin-build
          path: wp-content/plugins/toutefois/build
          merge-multiple: true

      - name: Deploy backend files via rsync
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --exclude='.git*' --exclude='frontend/' --exclude='node_modules' --exclude='*.log'
          path: "./"
          remote_path: "/var/www/toutefois_app"
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure WordPress and Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            echo "=== WordPress & Nginx Configuration ==="
            # Configure WordPress
            sudo mkdir -p /var/www/wordpress/wp-content/{plugins,themes,uploads}
            sudo rsync -avz --delete /var/www/toutefois_app/wp-content/plugins/ /var/www/wordpress/wp-content/plugins/
            sudo rsync -avz --delete /var/www/toutefois_app/wp-content/themes/ /var/www/wordpress/wp-content/themes/
            sudo find /var/www/wordpress/wp-content -type d -exec chmod 755 {} \;
            sudo find /var/www/wordpress/wp-content -type f -exec chmod 644 {} \;
            sudo chown -R www-data:www-data /var/www/wordpress/wp-content
            # Configure Nginx for WordPress Admin
            sudo cp /var/www/toutefois_app/nginx/sites-available/admin.toutefois.arianeguay.ca.conf /etc/nginx/sites-available/
            sudo ln -sf /etc/nginx/sites-available/admin.toutefois.arianeguay.ca.conf /etc/nginx/sites-enabled/admin.toutefois.arianeguay.ca.conf
            # Reload services
            sudo systemctl reload nginx
            sudo systemctl reload php8.4-fpm
            echo "=== Backend Deployed Successfully ==="
